import os
import asyncio
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER

class PDFGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self._setup_styles()
    
    def _setup_styles(self):
        """Setup custom styles for PDF"""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Title'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a2e'),
            spaceAfter=30
        ))
        
        self.styles.add(ParagraphStyle(
            name='Question',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor=colors.HexColor('#16213e'),
            spaceBefore=15,
            spaceAfter=5
        ))
        
        self.styles.add(ParagraphStyle(
            name='Answer',
            parent=self.styles['Normal'],
            fontSize=11,
            textColor=colors.HexColor('#0f3460'),
            leftIndent=20,
            spaceAfter=10
        ))
        
        self.styles.add(ParagraphStyle(
            name='Working',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#533483'),
            leftIndent=40,
            spaceAfter=10
        ))
    
    async def generate_bookwork_pdf(self, user_id: int, homework: dict, questions: list, settings: dict) -> str:
        """Generate a PDF of bookwork for the homework"""
        try:
            # Create PDF filename
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"bookwork_{user_id}_{timestamp}.pdf"
            filepath = os.path.join('pdfs', filename)
            
            # Ensure directory exists
            os.makedirs('pdfs', exist_ok=True)
            
            # Create PDF document
            doc = SimpleDocTemplate(
                filepath,
                pagesize=A4,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=72
            )
            
            # Build PDF content
            story = []
            
            # Title
            title = Paragraph(f"Sparx Maths Bookwork", self.styles['CustomTitle'])
            story.append(title)
            
            # Homework info
            info_data = [
                ["Homework:", homework.get('title', 'N/A')],
                ["Date:", datetime.now().strftime("%B %d, %Y")],
                ["Student ID:", str(user_id)]
            ]
            
            info_table = Table(info_data, colWidths=[1.5*inch, 4.5*inch])
            info_table.setStyle(TableStyle([
                ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
                ('FONTSIZE', (0,0), (-1,-1), 10),
                ('TEXTCOLOR', (0,0), (0,-1), colors.HexColor('#0f3460')),
                ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#e8e8e8')),
                ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('PADDING', (0,0), (-1,-1), 6),
            ]))
            
            story.append(info_table)
            story.append(Spacer(1, 20))
            
            # Questions and answers
            for i, question in enumerate(questions, 1):
                # Question
                q_text = question.get('text', 'N/A')
                q_para = Paragraph(f"<b>Question {i}:</b> {q_text}", self.styles['Question'])
                story.append(q_para)
                
                # Answer (if enabled)
                if settings.get('pdf_answers', True):
                    answer = question.get('answer', 'N/A')
                    a_para = Paragraph(f"<b>Answer:</b> {answer}", self.styles['Answer'])
                    story.append(a_para)
                
                # Working out (if enabled)
                if settings.get('pdf_working', True):
                    working = question.get('working', '')
                    if working:
                        w_para = Paragraph(f"<b>Working:</b> {working}", self.styles['Working'])
                        story.append(w_para)
                
                story.append(Spacer(1, 10))
            
            # Footer
            footer = Paragraph(
                f"Generated by VoboAi • {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
                ParagraphStyle(
                    'Footer',
                    parent=self.styles['Normal'],
                    fontSize=8,
                    textColor=colors.grey,
                    alignment=TA_CENTER
                )
            )
            story.append(Spacer(1, 30))
            story.append(footer)
            
            # Build PDF
            doc.build(story)
            
            return filepath
            
        except Exception as e:
            print(f"Error generating PDF: {e}")
            return None
