services:
  - type: web
    name: voboai
    runtime: python
    plan: free
    pythonVersion: 3.11.7
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
